# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: local
    hooks:
      - id: ruff-check
        name: ğŸ¶ Ruff Linter
        language: system
        types: [python]
        entry: scripts/run-in-env.sh ruff check --fix
        require_serial: true
        stages: [pre-commit, pre-push, manual]
      - id: ruff-format
        name: ğŸ¶ Ruff Formatter
        language: system
        types: [python]
        entry: scripts/run-in-env.sh ruff format
        require_serial: true
        stages: [pre-commit, pre-push, manual]
      - id: check-ast
        name: ğŸ Check Python AST
        language: system
        types: [python]
        entry: scripts/run-in-env.sh check-ast
      - id: check-case-conflict
        name: ğŸ”  Check for case conflicts
        language: system
        entry: scripts/run-in-env.sh check-case-conflict
      - id: check-docstring-first
        name: â„¹ï¸  Check docstring is first
        language: system
        types: [python]
        entry: scripts/run-in-env.sh check-docstring-first
      - id: check-executables-have-shebangs
        name: ğŸ§ Check that executables have shebangs
        language: system
        types: [text, executable]
        entry: scripts/run-in-env.sh check-executables-have-shebangs
        stages: [pre-commit, pre-push, manual]
      - id: check-json
        name: ï½› Check JSON files
        language: system
        types: [json]
        entry: scripts/run-in-env.sh check-json
      - id: check-merge-conflict
        name: ğŸ’¥ Check for merge conflicts
        language: system
        types: [text]
        entry: scripts/run-in-env.sh check-merge-conflict
      - id: check-symlinks
        name: ğŸ”— Check for broken symlinks
        language: system
        types: [symlink]
        entry: scripts/run-in-env.sh check-symlinks
      - id: check-toml
        name: âœ… Check TOML files
        language: system
        types: [toml]
        entry: scripts/run-in-env.sh check-toml
      - id: codespell
        name: âœ… Check code for common misspellings
        language: system
        types: [text]
        entry: scripts/run-in-env.sh codespell
      - id: detect-private-key
        name: ğŸ•µï¸  Detect Private Keys
        language: system
        types: [text]
        entry: scripts/run-in-env.sh detect-private-key
      - id: end-of-file-fixer
        name: â®  Fix End of Files
        language: system
        types: [text]
        entry: scripts/run-in-env.sh end-of-file-fixer
        stages: [pre-commit, pre-push, manual]
      - id: no-commit-to-branch
        name: ğŸ›‘ Don't commit to main branch
        language: system
        entry: scripts/run-in-env.sh no-commit-to-branch
        pass_filenames: false
        always_run: true
        args:
          - --branch=main
      - id: pylint
        name: ğŸŒŸ Starring code with pylint
        language: system
        types: [python]
        entry: scripts/run-in-env.sh pylint
      - id: trailing-whitespace
        name: âœ„  Trim Trailing Whitespace
        language: system
        types: [text]
        entry: scripts/run-in-env.sh trailing-whitespace-fixer
        stages: [pre-commit, pre-push, manual]
      - id: mypy
        name: mypy
        entry: scripts/run-in-env.sh mypy
        language: script
        types: [python]
        require_serial: true
        files: ^(matter_server|pylint)/.+\.py$
