commission:
  name: Commission device
  description: >
    Add a new device to your Matter network.
  fields:
    code:
      name: Pairing code
      required: true
      selector:
        text:
set_wifi:
  name: Set Wi-Fi credentials
  description: >
    The Wi-Fi credentials will be sent as part of comissioning to a Matter device so it can connect to the Wi-Fi network.
  fields:
    network_name:
      name: Network name
      required: true
      selector:
        text:
    password:
      name: Password
      required: true
      selector:
        text:
          type: password
set_thread:
  name: Set Thread network operational dataset
  description: >
    The Thread keys will be used as part of comissioning to let a Matter device join the Thread network.

    Get keys by running `ot-ctl dataset active -x` on the Open Thread Border Router.
  fields:
    thread_operation_dataset:
      name: Thread Operational Dataset
      required: true
      selector:
        text:
open_commissioning_window:
  name: Open Commissioning Window
  description: >
    Allow adding one of your devices to another Matter network by opening the commissioning window for this Matter device for 60 seconds.
  fields:
    device_id:
      name: Device
      required: true
      selector:
        device:
          integration: matter_experimental
