commission:
  name: Commission device
  description: >
    Commission a new device
  fields:
    code:
      name: Pairing code
      required: true
      selector:
        text:
set_wifi:
  name: Set Wi-Fi credentials
  description: >
    This is needed to set-up new Wi-Fi devices.
  fields:
    network_name:
      name: Network name
      required: true
      selector:
        text:
    password:
      name: Password
      required: true
      selector:
        text:
          type: password
set_thread:
  name: Set Thread network operational dataset
  description: >
    Required to set-up new Thread devices. Use "ot-ctl dataset active -x" on the OTBR.
  fields:
    thread_operation_dataset:
      name: Thread Operational Dataset
      required: true
      selector:
        text:
